apiVersion: v1
kind: Service
metadata:
  name: gaamingzhang-blog-service
  namespace: default
spec:
  selector:
    app: gaamingzhang-blog
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort
