apiVersion: v1
kind: Secret
metadata:
  name: registry-auth
  namespace: container-registry
type: Opaque
data:
  HTPASSWD: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-tls
  namespace: container-registry
type: kubernetes.io/tls
data:
  tls.crt: ""
  tls.key: ""
