apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: container-registry
  labels:
    app: docker-registry
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    name: https
  selector:
    app: docker-registry
---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry-nodeport
  namespace: container-registry
  labels:
    app: docker-registry
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30500
    name: https
  selector:
    app: docker-registry
